/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIPrimitive */

#ifndef _Included_TestJNIPrimitive
#define _Included_TestJNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_TestJNIPrimitive_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
